name: CI/CD Pipeline

on:
  push:
    branches: [main]
#chenking
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2


      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REPO }}:latest .
          docker tag ${{ secrets.ECR_REPO }}:latest ${{ secrets.ECR_URI }}:latest
          docker push ${{ secrets.ECR_URI }}:latest

      - name: Update ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: medusa-cluster
          service: medusa-service
          task-definition: medusa-task
