name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo so Dockerfile and source code are available
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Configure AWS credentials for ECR and ECS access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 4: Login to Amazon ECR to push images
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build Docker image, tag it with ECR repo URI, then push
      - name: Build, tag, and push Docker image
        run: |
          docker build -t medusa:latest .
          docker tag medusa:latest 970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest
          docker push 970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest

      # Step 6: Debug - list images in ECR repository (optional)
      - name: List images in ECR (debug)
        run: aws ecr list-images --repository-name medusa --region ap-south-1

      # Step 7: Update ECS task definition file with new Docker image URI
      - name: Update ECS task definition with new image
        id: update-task-def
        run: |
          jq '.containerDefinitions[0].image = "970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest"' medusa-task.json > new-task-def.json

      # Step 8: Show the updated task definition for verification
      - name: Debug — Show updated task definition
        run: cat new-task-def.json

      # Step 9: Deploy the updated task definition to ECS service
      - name: Deploy to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: medusa-cluster
          service: medusa-service
          task-definition: new-task-def.json
