name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository (for task def files like medusa-task.json)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Clone Medusa open-source project
      - name: Clone Medusa project
        run: git clone https://github.com/medusajs/medusa.git

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 5: Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 6: Build, tag, and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          docker build -t medusa:latest ./medusa
          docker tag medusa:latest 970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest
          docker push 970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest

      # Step 7: Debug — List images in ECR
      - name: List images in ECR (debug)
        run: aws ecr list-images --repository-name medusa --region ap-south-1

      # Step 8: Update ECS task definition with new image
      - name: Update ECS task definition with new image
        id: update-task-def
        run: |
          jq '.containerDefinitions[0].image = "970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest"' medusa-task.json > new-task-def.json

      # Step 9: Debug — Show updated task definition
      - name: Debug — Show updated task definition
        run: cat new-task-def.json

      # Step 10: Deploy updated task to ECS
      - name: Deploy to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: medusa-cluster
          service: medusa-service
          task-definition: new-task-def.json
