name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t medusa:latest .
          docker tag medusa:latest 970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest
          docker push 970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest

      - name: List images in ECR (debug)
        run: aws ecr list-images --repository-name medusa --region ap-south-1

      - name: Update ECS task definition with new image
        id: update-task-def
        run: |
          # Replace the image field inside containerDefinitions[0]
          jq '.containerDefinitions[0].image = "970547337517.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest"' medusa-task.json > new-task-def.json

      - name: Debug — Show updated task definition
        run: cat new-task-def.json

      - name: Deploy to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: medusa-cluster
          service: medusa-service
          task-definition: new-task-def.json
